config.menu.titulomenu = bienvenido al apicativo de la casa de apuestas
config.menu.textomenu = --- casade apuestas --- \n1) crear casa de puestas \n2) modificar parametros de la casa de apuestas\n3) salir \n
config.menu.textoguadado= --- desea guardar los cambios? ---

config.menu.exitoguardado= --- cambios guardados con exito ---
config.crear.nombredecasa= digite el nombre de la casa de apuetas :
config.crear.numerodesedes= numero de sedes que va a tener la casa:
config.crear.presupuesto= digite el presupuesto que tiene la casa para entregar los premios:


config.modificar.nombredecasa= digite el nuevo nombre de la casa de apuetas :
config.modificar.numerodesedes= numero el nuevo numero de sedes que va a tener la casa:
config.modificar.presupuesto= digite el nuevo presupuesto que tiene la casa para entregar los premios:



