config.menu.titulomenu = bienvenido al apicativo de la casa de apuestas
config.menu.textomenu = --- casade apuestas --- \n1) crear casa de puestas \n2) modificar parametros de la casa de apuestas\n3) salir \n
config.menu.textoguadado= --- desea guardar los cambios? ---

config.menuexitoguardado= --- cambios guardados con exito ---
config.crearnombredecasa= digite el nombre de la casa de apuetas :
config.crearnumerodesedes= numero de sedes que va a tener la casa:
config.crearpresupuesto= digite el presupuesto que tiene la casa para entregar los premios:


config.modificarnombredecasa= digite el nuevo nombre de la casa de apuetas :
config.modificarnumerodesedes= numero el nuevo numero de sedes que va a tener la casa:
config.modificarpresupuesto= digite el nuevo presupuesto que tiene la casa para entregar los premios:



