sedes.menu.titulomenu = bienvenido al apicativo de las sedes
sedes.menu.textomenu = --- enciclopedia de tuburones --- \n1) crear un tiburon \n2) leer todos los tuburones\n3) actualizar tiburon por index \n4) borrar tiburon por index \n5) vemos grr \n



sedes.actualizar.direccion=Nueva solución vive en agua salada:
sedes.actualizar.barrio=Error en actualizar
sedes.actualizar.localidad=Nuevo id:
sedes.actualizar.index=Index para actualizar:
sedes.actualizar.numEmpleados=Nuevo nombre
sedes.crear.direccion=Vive en agua salada:
sedes.crear.barrio=Id
sedes.crear.localidad=Nombre:
sedes.crear.numEmpleados=Nombre Cientifico:
sedes.eliminar.error=Error en eliminar
sedes.eliminar.index=Index para eliminar
sedes.eliminar.datoseliminados=dato eliminado eliminado
